### ISSUE TITLE
Support Migrations

### ISSUE THREAD

**Issue by paulirwin** [paulirwin/EntityFramework6-DotNetStandard#1]

**Comment by milosloub** [comment]
Hello, this is extremelly good EF6 port, it helped me a lot. Is there some progress with migrations? Or is it difficult to implement default initializers like DropCreateDatabaseIfModelChanges ?

**Comment by paulirwin** [comment]
@milosloub That is up for grabs by the community. I do not have the time, desire, nor real-world test case in my application to complete this. I'd imagine the initializers would be easier to do than the PowerShell side of things.

As an aside, I'm also against the whole concept of EF migrations, and prefer SQL Server Database Projects instead. But people keep asking for it, so I'll gladly accept PRs 😄

**Comment by patrikwlund** [comment]
Added a PR for this (#2). Lacks tooling support, but you can still use vanilla EF6 for that.

**Comment by paulirwin** [comment]
Resolved by #2
